#!/usr/bin/env bash
function sshrc() {
local SSHHOME=${SSHHOME:=~/flant/sshrc}
local files=`ls -A $SSHHOME | grep -v -E "^(.git|README|LICENSE)"`
SIZE=$(tar cfz - -h -C $SSHHOME $files | wc -c)
if [ ${SIZE} -gt 65536 ]; then echo >&2 $'files must be less than 64kb\ncurrent size: '$SIZE' bytes'; exit 1; fi
ssh -t "$DOMAIN" $SSHARGS "
command -v base64 >/dev/null 2>&1 || { echo >&2 \"sshrc requires base64\"; exit 1; }
export SSHHOME=\$(mktemp -d -p /dev/shm/ -t .$(whoami).sshrc.XXXX)
export SSHRCCLEANUP=\$SSHHOME

echo $(tar cfz - -h -C $SSHHOME $files | base64 -w0) | base64 -d | tar mxzf - -C \$SSHHOME
export SSHHOME=\$SSHHOME
export CLIENT=`echo $DOMAIN | grep -Po '^(?!.*@)([^.]+)'`
echo \"$CMDARG\" >> \$SSHHOME/.bashrc
exec bash --rcfile \$SSHHOME/.bashrc
"
}

function sshrc_parse() {
  while [[ -n $1 ]]; do
    case $1 in
      -B | -b | -c | -D | -E | -e | -F | -I | -i | -J | -L | -l | -m | -O | -o | -p | -Q | -R | -S | -W | -w )
        SSHARGS="$SSHARGS $1 $2"; shift ;;
      -* )
        SSHARGS="$SSHARGS $1" ;;
      *)
        if [ -z "$DOMAIN" ]; then
         DOMAIN="$1"
        else
          local SEMICOLON=$([[ "$@" = *[![:space:]]* ]] && echo '; ')
          CMDARG="$@$SEMICOLON exit"
          return;
        fi
        ;;
    esac
    shift
  done
  if [ -z $DOMAIN ]; then
    ssh $SSHARGS; exit 1;
  fi
}

command -v base64 >/dev/null 2>&1 || { echo >&2 "sshrc requires base64 to be installed locally, but it's not. Aborting."; exit 1; }
sshrc_parse "$@"
sshrc
